language: r
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'

    packages:
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - liblwgeom-dev

sudo: required
dist: trusty

before_install:
 - sudo ldconfig
