language: r
cache: packages

addons:
  apt:
    sources:
      - sourceline: 'ppa:opencpu/jq'

    packages:
      - libgdal-dev
      - libproj-dev
      - libgeos-dev
      - liblwgeom-2.1.2

sudo: required
dist: trusty

before_install:
before_install:
  # install postgis from source:
  - wget http://download.osgeo.org/postgis/source/postgis-2.3.2.tar.gz
  - (mv postgis* /tmp; cd /tmp; tar xzf postgis-2.3.2.tar.gz)
  - (cd /tmp/postgis-2.3.2 ; ./configure; make; sudo make install)

  # activate liblwgeom by:
  - sudo ldconfig
